---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - heka

- name: install > Lua encoders
  template:
    src:  "lua_encoders/{{ item }}.j2"
    dest: "/usr/share/heka/lua_encoders/{{ item }}.lua"
  with_items:
    - rtail
